#lg_core:
#    resource: "@LGCoreBundle/Resources/config/routing.yml"
#    prefix:   /

lg_core:
    resource: "@LGCoreBundle/Controller"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
