# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    get_set_method_normalizer:
        class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
        public: false
        tags:
            - { name: serializer.normalizer }
#    booking_token_listener:
#        class: LG\CoreBundle\Entity\EntityListener\BookingTokenListener
#        tags:
#            - { name: doctrine.orm.entity_listener }
#            - { name: doctrine.orm.entity_listener, entity_manager: custom }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]