services:
#    lg_core.example:
#        class: LG\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  lg_core_bundle.normalizer.client:
    class: LG\CoreBundle\Normalizer\ClientNormalizer
    tags:
      - { name: serializer.normalizer }

  lg_core_bundle.validator.limittickets:
      class: LG\CoreBundle\Validator\LimitTicketsValidator
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: validator.constraint_validator, alias: lg_core_bundle_limittickets }

  lg_core_bundle.stripe:
      class: LG\CoreBundle\Stripe\Stripe

  lg_core_bundle.bookingprovider:
      class: LG\CoreBundle\Provider\BookingProvider

  lg_core_bundle.notallowedtobehere:
      class: LG\CoreBundle\NotAllowedToBeHere\NotAllowedToBeHere