<?php

namespace LG\CoreBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * With this function, we can get all booking dates from today.
     * 
     * The query is refined according to the status of the order.
     * If it's paid OR if it's not paid but has been add to basket less than an hour ago -> we take it into account.
     * If not, we don't take it into account.
     * Indeed, tickets that have not resulted in a payment are logically still on sale and must not fall under the constraint.
     * 
     * @return array
     */
    public function findByDateReservation()
    {
        //Variables we need
        $day = date('d');
        $dayYesterday = $day - 1;
        $month = date('m');
        $year = date('Y');
        $currentTimestamp = date('YmdHis', time());
        // If we don't check that, we can't get date reservation after current date (for example, with 2017033 for current date, query doesn't work. We must have 20170303)
        if ($dayYesterday < 10){
            $dayYesterday = '0'.$dayYesterday;
        }
        $currentDate = $year.$month.$dayYesterday;
        
        //Query Builder
        $qd = $this->createQueryBuilder('b');
        $qd
            ->select('b')
            ->where('b.dateReservation > :currentDate')
                ->setParameter('currentDate', $currentDate)
            ->andWhere('b.stateOrder = 3 OR b.anHourAfterBooking > :currentTimestamp')
                ->setParameter(':currentTimestamp', $currentTimestamp);
        
        return $qd->getQuery()->getResult();
    }

    /**
     * @param $token
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findByToken($token) {
        $qb = $this->createQueryBuilder('b');
        $qb->select('b')
            ->where('b.token = :token')
            ->setParameter('token', $token['token']);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
