<?php

namespace LG\CoreBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDateReservation()
    {
        $currentDate = new \DateTime();
        
        $qd = $this->createQueryBuilder('b');
        
        $qd
            ->select('b')
            ->where('b.dateReservation >= :currentDate')->setParameter('currentDate', $currentDate);
        
        return $qd->getQuery()->getResult();
    }
}
