<?php

namespace LG\CoreBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * We get the name client.
     * @param $bookingId
     * @return array
     */
    public function getClientsNameById($bookingId){
        
        $qd = $this->createQueryBuilder('c');
        
        $qd
            ->select('c.lastName', 'c.firstName')
            ->where('c.booking = :bookingId')->setParameter('bookingId', $bookingId);
        
        return $qd->getQuery()->getResult();
    }
}
